name: Manage Release
on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/ci.yaml
    with:
      distribute: true
  release-pr:
    name: "Release Please"
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: "Generate access token"
        id: gentoken
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RELEASE_MANAGER_APP_ID }}
          private-key: ${{ secrets.RELEASE_MANAGER_PRIVATE_KEY }}
      - name: "Check out code"
        uses: actions/checkout@v4
      - name: "Create/update release PR"
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ steps.gentoken.outputs.token }}
          skip-github-release: true
